This commit contains some small changes to catch blocks and tests
daniel-fitzg/PipelineProject pull request #16
Opened 2020-05-01 12:55 UTC by dshirt

Made very small changes to catch block in Employee constructor. The catch had thrown a new exception before and now prints a statement. new test wrote for this.
another catch also changed in employee class and test written for same reason.
new method writtten for invalidDOBformatt in Employeefactory.

2020-05-01 13:41 UTC, rdmoraes commented on src/main/java/employee/com/Employee.java
> +          System.out.println("Employee date of birth must be in format dd/MM/yyyy");
Why did you change it to output stream?

2020-05-01 13:45 UTC, daniel-fitzg requested changes

2020-05-01 13:45 UTC, daniel-fitzg commented on src/test/java/employee/com/CommissionBasedStaffTest.java
>      }
Is this change no longer testing anything? Not seeing any assert statements.

2020-05-01 13:45 UTC, daniel-fitzg commented on src/test/java/employee/com/CommissionBasedStaffTest.java
> +        EmployeeFactory.getInvalidEmployeDOBFormat();
Are you testing anything in here? No asserts.

2020-05-01 13:45 UTC, daniel-fitzg commented on src/test/java/employee/com/EmployeeFactory.java
> +    static CommissionBasedStaff getInvalidEmployeDOBFormat() {
Could you change the name of the method to:
getComissionBasedStaffWithInvalidDOB()

I think it makes more sense.

2020-05-01 13:46 UTC, rdmoraes commented on src/test/java/employee/com/CommissionBasedStaffTest.java
> +        EmployeeFactory.getValidCommissionBasedStaff().setEmployeeId("AAA");
As you import  **employee.com.EmployeeFactory.getValidCommissionBasedStaff** (line 3) I would change to **employee.com.EmployeeFactory.*** and rewrite this line as _getValidCommissionBasedStaff().setEmployeeID("AAA")_

2020-05-01 13:48 UTC, rdmoraes commented on src/test/java/employee/com/CommissionBasedStaffTest.java
> +        EmployeeFactory.getInvalidEmployeDOBFormat();
Same here **EmployeeFactory.getInvalidEmployeeDOBFormat()** to **getInvalidEmployeeDOBFormat()**

2020-05-01 13:50 UTC, rdmoraes commented on src/test/java/employee/com/EmployeeFactory.java
> +    static CommissionBasedStaff getInvalidEmployeDOBFormat() {
Minor typo in  getInvalidEmploye*e*DOBFormat()

2020-05-01 13:53 UTC, rdmoraes requested changes
Minor changes required

2020-05-02 13:33 UTC, dshirt commented on src/main/java/employee/com/Employee.java
> +            new EmployeeValidationService();
This is the only way i could make this work if it was moved into constructor it broke the code

2020-05-02 13:47 UTC, daniel-fitzg requested changes
Just a few little things left.

2020-05-02 13:47 UTC, daniel-fitzg commented on src/main/java/employee/com/DepartmentManager.java
> +import java.text.ParseException;
Unused import statement.

2020-05-02 13:47 UTC, daniel-fitzg commented on src/main/java/employee/com/Director.java
> +import java.text.ParseException;
Unused import.

2020-05-02 13:47 UTC, daniel-fitzg commented on src/main/java/employee/com/Employee.java
>  import java.text.SimpleDateFormat;
Unused imports.

2020-05-02 13:47 UTC, daniel-fitzg commented on src/main/java/employee/com/Employee.java
> +    EmployeeValidationService employeeValidationService =
Can be private.

2020-05-02 13:47 UTC, daniel-fitzg commented on src/main/java/employee/com/Manager.java
> +import java.text.ParseException;
Unused import.

2020-05-02 14:11 UTC, daniel-fitzg commented on src/main/java/employee/com/Employee.java
> +            new EmployeeValidationService();
@dshirt I just meant the variable could be private instead of package-private

2020-05-02 17:37 UTC, daniel-fitzg approved these changes
LGTM

2020-05-02 18:02 UTC, rdmoraes approved these changes
Looks good to me as well! Are we back with the validation class again?

2020-05-02 21:45 UTC, daniel-fitzg commented
@rdmoraes I think the setters were just getting too big and messy. Moving into it's own  class seemed a cleaner solution.

2020-05-02 21:50 UTC, merged