John branch
daniel-fitzg/PipelineProject pull request #2
Opened 2020-04-25 12:21 UTC by dshirt

The code adds the following three classes:

1. CommissionBasedEmployee ........(this extends employee and is a class for an employee who has earnings solely from commission of sales)
2. BasicPlusCommissionBasedEmployee........(This extends ComissionBasedEmployee and is a class to represent those sales employees who have a mixed income, basic wage and commission)
3. HourlyrateEmployees.......(This class extends Employee and represents employees whose wage is calculated by the hours they work, over 40 hrs and they move to a different rate)

2020-04-26 12:14 UTC, daniel-fitzg requested changes
Looks good overall, John. Mostly just a few formatting changes needed.

2020-04-26 12:14 UTC, daniel-fitzg commented on src/main/java/employee/com/CommissionBasedEmployee.java
> +        return payment;
Could be combined into a single line, see above comment.

2020-04-26 12:14 UTC, daniel-fitzg commented on src/main/java/employee/com/HourlyRateEmployee.java
> +
Watch out for multi-line spacing, keep it to one line.

2020-04-26 12:14 UTC, daniel-fitzg commented on src/main/java/employee/com/BasicPlusCommissionBasedEmployee.java
> +        return payment;
Could be combined into a single line:

return (getValueOfIndividualSales() * getCommissionRate()) + basicWage;

2020-04-26 12:14 UTC, daniel-fitzg commented on src/main/java/employee/com/HourlyRateEmployee.java
> +        if(hoursWorked > 40){
Can we have a final variable for the 40 hours? Something like:
private final int OVERTIME_CUTOFF_HOURS = 40;
Placed at the top of the class.

2020-04-26 12:14 UTC, daniel-fitzg commented on src/main/java/employee/com/HourlyRateEmployee.java
> +        }else
Minor formatting: Can you put the {} in the else statement. Even though there is only a single line of code within the else, it's a common source of bugs in large and complex code bases (Ours is small but it's good practice in industry, for Java anyway.)

2020-04-26 12:14 UTC, daniel-fitzg commented on src/main/java/employee/com/HourlyRateEmployee.java
> +        return payment;
As above , return statement can be combines into line 40 and 38.

2020-04-26 12:47 UTC, daniel-fitzg commented
@dshirt We have a ManagerService class now and I was going to add the service class for non-managers. To keep the naming from becoming confusing I was going to call it staffService. This way it doesn't clash with the abstract class Employee (because the Manager classes inherit from Employee as well). That being the case, what do you think about renaming you classes here from CommissionBasedEmployee -> CommissionBasedStaff, HourlyRateStaff etc...

What do you think?

2020-04-28 07:43 UTC, rdmoraes requested changes
Hi John looks great for me just need the cosmetic changes Daniel mentioned before

2020-04-28 09:20 UTC, dshirt commented
Changes to the class have been made as requested, also test classes added

2020-04-28 09:57 UTC, daniel-fitzg requested changes

2020-04-28 09:57 UTC, daniel-fitzg commented on src/main/java/employee/com/BasicPlusCommissionBasedStaff.java
> +        if(basicWage < 420){
Magic number. Can we make a final variable here for 420?

2020-04-28 09:57 UTC, daniel-fitzg commented on src/main/java/employee/com/BasicPlusCommissionBasedStaff.java
> +            throw new IllegalArgumentException("Basic wage cannot be less than €420 a week ");
Final variable from above line can be used here in error the print statement too.

2020-04-28 09:57 UTC, daniel-fitzg commented on src/main/java/employee/com/CommissionBasedStaff.java
> +        if(commissionRate <= 0 || commissionRate >=0.20){
Zero commission rate is ok, but can make a class variable for the 0.20. 

Something like: HIGHER_COMMISSIO_RATE_CUTOFF

2020-04-28 09:57 UTC, daniel-fitzg commented on src/main/java/employee/com/Employee.java
> +    public void setEmployeeId(int employeeId) {
Why did you convert EmployeeId from String to int here? If it is a String we can check the length and content of the ID, int is a lot harder to work with.

2020-04-28 09:57 UTC, daniel-fitzg commented on src/main/java/employee/com/HourlyRateStaff.java
> +
Line spacing.

2020-04-28 09:57 UTC, daniel-fitzg commented on src/main/java/employee/com/HourlyRateStaff.java
> +        if(hourlyRate < 10.50){
Can we convert magic number to another class variable for MINIMUM_WAGE and add into error print statement too.

2020-04-28 09:57 UTC, daniel-fitzg commented on src/test/java/employee/com/BasicPlusCommissionBasedStaffTest.java
> +    void getBasicWage() {
Are these tests to be written later?

2020-04-28 09:57 UTC, daniel-fitzg commented on src/test/java/employee/com/CommissionBasedStaffTest.java
> +    CommissionBasedStaff employee;
Can be private.

2020-04-28 09:57 UTC, daniel-fitzg commented on src/main/java/employee/com/Employee.java
> +            this.dob = dob;
This is cool. Dates are very tricky.

2020-04-28 10:43 UTC, dshirt commented on src/main/java/employee/com/Employee.java
> +    public void setEmployeeId(int employeeId) {
Changed it to int because of a comment Paul had made about a phone number I had written code for in one of his labs. He said that the number could have been filled with any chars and would have passed the test. When we say EmpoyeeId can it be a mixture of numbers and letters?

2020-04-28 10:47 UTC, daniel-fitzg commented on src/main/java/employee/com/Employee.java
> +    public void setEmployeeId(int employeeId) {
It could be a mixture, but I was thinking it would just be a four-digit number. Like 1729.

2020-04-28 15:14 UTC, rdmoraes approved these changes

2020-04-28 15:14 UTC, rdmoraes commented on src/main/java/employee/com/HourlyRateEmployee.java
> +    private final double overtimeRate = hourlyRate *1.5;
I would change overtimeRate to OVERTIME_RATE as it is declared as a final double

2020-04-28 15:14 UTC, rdmoraes commented on src/main/java/employee/com/Employee.java
> +        }
Do you have test for this?

2020-04-28 22:25 UTC, closed without merging